// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ops-log/HierarchyVariant.tsx": () => import("../components/mockups/ops-log/HierarchyVariant.tsx"),
  "./components/mockups/osint-dashboard/AccessibilityFirst.tsx": () => import("../components/mockups/osint-dashboard/AccessibilityFirst.tsx"),
  "./components/mockups/osint-dashboard/AffordanceFirst.tsx": () => import("../components/mockups/osint-dashboard/AffordanceFirst.tsx"),
  "./components/mockups/osint-dashboard/HierarchyFirst.tsx": () => import("../components/mockups/osint-dashboard/HierarchyFirst.tsx")
};
